name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install --force

      - name: Set permission to Cypress binary
        run: chmod +x ./node_modules/.bin/cypress

      - name: Jalankan Cypress tests
        run: ./node_modules/.bin/cypress run

      - name: Upload Cypress video dan screenshot (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
